### ISSUE TITLE
Sync Errors with Rainbow 2.1.1 and SC Hotfix 400435-3 (Sc 9.3)

### ISSUE THREAD

**Issue by hombreDelPez** [SitecoreUnicorn/Rainbow#37]
Hi Mark / Kam

I'm not quite sure if this is the correct channel to address this issue (because it could also be a Sitecore bug) but maybe you know something in this regard.

Thanks :)

**Do you want to request a *feature* or report a *bug*?**
A possible bug in Rainbow, Unicorn or Sitecore.

**What is the current behavior?**
If a (language) version is missing in the YML file (compared to the item in the database), Unicorn tries to delete this version (like it is supposed to) -> but this results in an Error like the following one:

![sync-error](https://user-images.githubusercontent.com/20950007/83039798-db8ba500-a03e-11ea-9002-58844474513a.png)

```
25272 16:59:30 ERROR Failed to remove the item version. Item ID: {6974D84F-1212-4671-BAFE-0FDE31C3EE38}, version: 1, language: de-CH
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Sitecore.Kernel
   at Sitecore.Data.DataSource.RemoveVersion(ID itemID, VersionUri uri)
   at Sitecore.Nexus.Data.DataCommands.RemoveVersionCommand.‪⁫⁯‪‬⁪⁮​‍‫⁬⁮‎‍⁭⁯‫⁪⁬⁫‏‫‫‫⁭‫‮​‫⁮‎‬‭⁫⁭⁫⁭‍‌‮‮(Item )
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.RemoveVersion(Item item)

25272 16:59:30 INFO  [Unicorn]: * [D] de-CH#1
25272 16:59:30 ERROR Failed to remove the item version. Item ID: {6974D84F-1212-4671-BAFE-0FDE31C3EE38}, version: 1, language: de-CH
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Sitecore.Kernel
   at Sitecore.Data.DataSource.RemoveVersion(ID itemID, VersionUri uri)
   at Sitecore.Nexus.Data.DataCommands.RemoveVersionCommand.‪⁫⁯‪‬⁪⁮​‍‫⁬⁮‎‍⁭⁯‫⁪⁬⁫‏‫‫‫⁭‫‮​‫⁮‎‬‭⁫⁭⁫⁭‍‌‮‮(Item )
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.RemoveVersion(Item item)

25272 16:59:30 INFO  [Unicorn]: * [D] de-CH#1
25272 16:59:30 ERROR Failed to remove the item version. Item ID: {6974D84F-1212-4671-BAFE-0FDE31C3EE38}, version: 1, language: de-CH
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Sitecore.Kernel
   at Sitecore.Data.DataSource.RemoveVersion(ID itemID, VersionUri uri)
   at Sitecore.Nexus.Data.DataCommands.RemoveVersionCommand.‪⁫⁯‪‬⁪⁮​‍‫⁬⁮‎‍⁭⁯‫⁪⁬⁫‏‫‫‫⁭‫‮​‫⁮‎‬‭⁫⁭⁫⁭‍‌‮‮(Item )
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.RemoveVersion(Item item)

25272 16:59:30 INFO  [Unicorn]: * [D] de-CH#1
25272 16:59:30 ERROR ERROR: Some directories could not be loaded. (1 inner failures)
master:/sitecore/templates/Feature/Bookmarks/Configuration/Bookmark Configuration (6974d84f-1212-4671-bafe-0fde31c3ee38) (Unicorn.DeserializationAggregateException)
at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)
   at Unicorn.Loader.SerializationLoader.LoadAll(IItemData[] rootItemsData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker, Action`1 rootLoadedCallback)
   at Unicorn.SerializationHelper.SyncTree(IConfiguration configuration, Action`1 rootLoadedCallback, Boolean runSyncStartPipeline, IItemData partialSyncRoot)
   at Unicorn.SerializationHelper.SyncConfigurations(IConfiguration[] configurations, IProgressStatus progress, ILogger additionalLogger)

INNER EXCEPTION
master:/sitecore/templates/Feature/Bookmarks/Configuration/Bookmark Configuration (6974d84f-1212-4671-bafe-0fde31c3ee38) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
Failed to paste item: /sitecore/templates/Feature/Bookmarks/Configuration/Bookmark Configuration (Rainbow.Storage.Sc.Deserialization.DeserializationException)
at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData, IFieldValueManipulator fieldValueManipulator)
   at Rainbow.Storage.Sc.SitecoreDataStore.Save(IItemData item, IFieldValueManipulator fieldValueManipulator)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.EvaluateUpdate(IItemData sourceItem, IItemData targetItem)
   at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)
INNER EXCEPTION
Object reference not set to an instance of an object. (System.NullReferenceException)
at Sitecore.Data.DataSource.RemoveVersion(ID itemID, VersionUri uri)
   at Sitecore.Nexus.Data.DataCommands.RemoveVersionCommand.‪⁫⁯‪‬⁪⁮​‍‫⁬⁮‎‍⁭⁯‫⁪⁬⁫‏‫‫‫⁭‫‮​‫⁮‎‬‭⁫⁭⁫⁭‍‌‮‮(Item )
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.RemoveVersion(Item item)
   at Sitecore.Data.Managers.ItemProvider.RemoveVersion(Item item, SecurityCheck securityCheck)
   at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.PasteVersions(IItemData serializedItemData, Item targetItem, Boolean newItemWasCreated, List`1 softErrors, IFieldValueManipulator fieldValueManipulator)
   at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData, IFieldValueManipulator fieldValueManipulator)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Make sure you have the SC Hotfix 400435-3 applied
- Delete a (language) version in a YML file and do a Unicorn sync.

**What is the expected behavior?**
Deletion of a (language) version should not cause an error.

**Please mention your Sitecore version, Rainbow version, and if also using Unicorn, your version of that too.**
- Sitecore 9.3 with SC Hotfix 400435-3
- Unicorn 4.1.2-pre1
- Rainbow 1.1.2

**Comment by cassidydotdk** [comment]
Hey, and thanks for the report. You are in the right place :-)

First off, can I assume you mean Rainbow 2.1.1 and not 1.1.2? :D  If so, that would indeed become a problem.

So about the hotfix; have you confirmed that this does not happen if the hotfix is NOT applied?  And do you have a public link to the hotfix or will I need to get hold of Sitecore Support directly for it?

Last question; do you have any of the language fallback settings enabled?

**Comment by hombreDelPez** [comment]
Hi Mark

Thank you for your fast reply :)

- I meant indeed **2.1.1** . I just corrected it in the text.
- Yeah, I tested it several times with and without this hotfix and everytime, when the hotfix was applied, this exception/error occured. I have never experienced this error before applying the hotfix.
- Unfortunately I don't have a public link. You will need to contact Sitecore Support for this hotfix.
- I hope this screenshot answers your question concerning fallback settings:
![image](https://user-images.githubusercontent.com/20950007/83067363-d80c1400-a066-11ea-9fd9-0341deaaf1c7.png)

Thanks for your investigation.

Best regards,
Manuel
